Repository zhenxun-org/zhenxun_bot, pull requests merged in 2024-11, with the labels that each got.

#1719 ✨ 添加用户消息撤回命令
  README.md
  docs_image/afd.jpg
  docs_image/webui0.png
  docs_image/webui1.png
  docs_image/webui2.png
  docs_image/webui3.png
  docs_image/webui4.png
  docs_image/webui5.png
  docs_image/webui6.png
  docs_image/webui7.png
  zhenxun/builtin_plugins/hooks/call_hook.py
  zhenxun/builtin_plugins/withdraw.py
  zhenxun/utils/manager/message_manager.py
Labels: documentation, enhancement

#1742 :tada: chore(version): 自动更新版本到 v0.2.4-dd39a2a
  __version__
Labels: automated-update

#1745 :tada: chore(version): 自动更新版本到 v0.2.4-6e74065
  __version__
Labels: automated-update

#1746 ⬆️ 提高pil依赖版本
  poetry.lock
  pyproject.toml
  zhenxun/builtin_plugins/hooks/_auth_checker.py
Labels: dependencies

#1747 :tada: chore(version): 自动更新版本到 v0.2.4-900cf6f
  __version__
Labels: automated-update

#1749 ✨ 插件配置新增is_show控制是否显示在菜单中
  zhenxun/builtin_plugins/help/__init__.py
  zhenxun/builtin_plugins/help/_utils.py
  zhenxun/builtin_plugins/init/init_plugin.py
  zhenxun/configs/utils/__init__.py
  zhenxun/models/plugin_info.py
Labels: enhancement

#1750 :tada: chore(version): 自动更新版本到 v0.2.4-c7c759f
  __version__
Labels: automated-update
