Repository zhenxun-org/zhenxun_bot, pull requests merged in 2024-12, with the labels that each got.

#1758 添加Bot管理插件
  .gitignore
  .pre-commit-config.yaml
  zhenxun/builtin_plugins/hooks/_auth_checker.py
  zhenxun/builtin_plugins/superuser/bot_manage/__init__.py
  zhenxun/builtin_plugins/superuser/bot_manage/bot_switch.py
  zhenxun/builtin_plugins/superuser/bot_manage/command.py
  zhenxun/builtin_plugins/superuser/bot_manage/full_function.py
  zhenxun/builtin_plugins/superuser/bot_manage/plugin.py
  zhenxun/builtin_plugins/superuser/bot_manage/task.py
  zhenxun/models/bot_console.py
  zhenxun/utils/common_utils.py
Labels: dependencies

#1760 :bug: fix bot console init
  zhenxun/builtin_plugins/superuser/bot_manage/__init__.py
  zhenxun/models/bot_console.py
Labels: bug

#1765 🐛 BotConsole添加迁移sql
  zhenxun/models/bot_console.py
Labels: bug

#1763 chore/cleanup-dependencies
  .pre-commit-config.yaml
  bot.py
  poetry.lock
  pyproject.toml
  requirements.txt
  zhenxun/utils/image_utils.py
Labels: dependencies

#1767 🐛 优化Bot管理插件，更新使用说明及代码结构
  zhenxun/builtin_plugins/superuser/bot_manage/__init__.py
  zhenxun/models/user_console.py
Labels: bug

#1759 :tada: chore(version): 自动更新版本到 v0.2.4-e363d29
  __version__
Labels: automated-update

#1783 🐛 修改webui导入路径
  pyproject.toml
  zhenxun/builtin_plugins/init/init_plugin.py
  zhenxun/builtin_plugins/shop/_data_source.py
  zhenxun/builtin_plugins/sign_in/goods_register.py
  zhenxun/builtin_plugins/web_ui/api/tabs/dashboard/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/dashboard/data_source.py
  zhenxun/builtin_plugins/web_ui/api/tabs/database/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/main/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/manage/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/manage/chat.py
  zhenxun/builtin_plugins/web_ui/api/tabs/plugin_manage/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/plugin_manage/store.py
  zhenxun/builtin_plugins/web_ui/api/tabs/system/__init__.py
  zhenxun/builtin_plugins/web_ui/auth/__init__.py
  zhenxun/builtin_plugins/web_ui/public/__init__.py
  zhenxun/builtin_plugins/web_ui/public/data_source.py
Labels: bug, dependencies

#1791 :bug: Fix help_type in create_help_img may be none and cause AttributeError.
  zhenxun/builtin_plugins/help/_data_source.py
Labels: bug

#1776 :tada: chore(version): 自动更新版本到 v0.2.4-4291cda
  __version__
Labels: automated-update

#1795 🐛 修复自检测试
  tests/builtin_plugins/check/test_check.py
Labels: bug

#1801 重构webui适配
  .markdownlint.yaml
  README.md
  resources/template/check/main.css
  zhenxun/builtin_plugins/__init__.py
  zhenxun/builtin_plugins/hooks/_auth_checker.py
  zhenxun/builtin_plugins/init/init_plugin.py
  zhenxun/builtin_plugins/restart/__init__.py
  zhenxun/builtin_plugins/scheduler/chat_check.py
  zhenxun/builtin_plugins/shop/__init__.py
  zhenxun/builtin_plugins/superuser/broadcast/_data_source.py
  zhenxun/builtin_plugins/web_ui/__init__.py
  zhenxun/builtin_plugins/web_ui/api/__init__.py
  zhenxun/builtin_plugins/web_ui/api/menu/__init__.py
  zhenxun/builtin_plugins/web_ui/api/menu/data_source.py
  zhenxun/builtin_plugins/web_ui/api/menu/model.py
  zhenxun/builtin_plugins/web_ui/api/tabs/dashboard/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/dashboard/data_source.py
  zhenxun/builtin_plugins/web_ui/api/tabs/database/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/database/data_source.py
  zhenxun/builtin_plugins/web_ui/api/tabs/main/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/main/data_source.py
  zhenxun/builtin_plugins/web_ui/api/tabs/main/model.py
  zhenxun/builtin_plugins/web_ui/api/tabs/manage/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/manage/chat.py
  zhenxun/builtin_plugins/web_ui/api/tabs/manage/data_source.py
  zhenxun/builtin_plugins/web_ui/api/tabs/manage/model.py
  zhenxun/builtin_plugins/web_ui/api/tabs/plugin_manage/__init__.py
  zhenxun/builtin_plugins/web_ui/api/tabs/plugin_manage/data_source.py
  zhenxun/builtin_plugins/web_ui/base_model.py
  zhenxun/services/__init__.py
  zhenxun/utils/common_utils.py
  zhenxun/utils/platform.py
Labels: documentation, resources
