Repository zhenxun-org/zhenxun_bot, pull requests merged in 2025-07, with the labels that each got.

#1948 :bug: 修复被动的默认开关指令
  zhenxun/builtin_plugins/admin/plugin_switch/__init__.py
  zhenxun/builtin_plugins/admin/plugin_switch/_data_source.py
  zhenxun/builtin_plugins/admin/plugin_switch/command.py
  zhenxun/builtin_plugins/platform/qq/group_handle/__init__.py
  zhenxun/builtin_plugins/superuser/broadcast/__init__.py
Labels: bug

#1925 :sparkles: 检查更新支持webui更新
  .vscode/settings.json
  tests/builtin_plugins/auto_update/test_check_update.py
  tests/utils.py
  zhenxun/builtin_plugins/auto_update/__init__.py
  zhenxun/builtin_plugins/auto_update/_data_source.py
  zhenxun/builtin_plugins/auto_update/config.py
Labels: enhancement

#1976 更新README.md
  README.md
Labels: documentation

#1979 :bug: 修复sqlite连接问题
  zhenxun/services/db_context.py
Labels: bug

#1822 :tada: chore(version): 自动更新版本到 v0.2.4-da6d5b4
  __version__
Labels: automated-update
