Repository zhenxun-org/zhenxun_bot, pull requests merged in 2025-01, with the labels that each got.

#1816 ✨ 新增全新商店界面
  resources/image/shop_icon/mysterious_potion.png
  resources/template/shop/main.css
  resources/template/shop/main.html
  resources/template/shop/main.js
  resources/template/shop/res/img/bag1.png
  resources/template/shop/res/img/bag2.png
  resources/template/shop/res/img/bag3.png
  resources/template/shop/res/img/head.png
  resources/template/shop/res/img/item-bk1.png
  resources/template/shop/res/img/item-bk2.png
  resources/template/shop/res/img/item-bk3.png
  resources/template/shop/res/img/left_right/1.png
  resources/template/shop/res/img/left_right/2.png
  resources/template/shop/res/img/left_right/3.png
  resources/template/shop/res/img/left_right/4.png
  resources/template/shop/res/img/left_right/5.png
  resources/template/shop/res/img/left_right/qq.png
  resources/template/shop/res/img/left_right/xx1.png
  resources/template/shop/res/img/left_right/xx2.png
  resources/template/shop/res/img/split.png
  resources/template/shop/res/img/title-bk.png
  zhenxun/builtin_plugins/shop/__init__.py
  zhenxun/builtin_plugins/shop/_data_source.py
  zhenxun/builtin_plugins/shop/config.py
  zhenxun/builtin_plugins/shop/goods_register.py
  zhenxun/builtin_plugins/shop/html_image.py
  zhenxun/builtin_plugins/shop/normal_image.py
  zhenxun/models/goods_info.py
  zhenxun/utils/decorator/shop.py
Labels: enhancement, resources

#1817 🐛 修复商品图标显示问题，移除测试道具
  zhenxun/builtin_plugins/shop/__init__.py
  zhenxun/builtin_plugins/shop/goods_register.py
  zhenxun/builtin_plugins/shop/html_image.py
Labels: bug

#1820 🐛 移除resources，图标不存在时不会显示图片
  resources/image/shop_icon/mysterious_potion.png
  resources/template/shop/main.css
  resources/template/shop/main.html
  resources/template/shop/main.js
  resources/template/shop/res/img/bag1.png
  resources/template/shop/res/img/bag2.png
  resources/template/shop/res/img/bag3.png
  resources/template/shop/res/img/head.png
  resources/template/shop/res/img/item-bk1.png
  resources/template/shop/res/img/item-bk2.png
  resources/template/shop/res/img/item-bk3.png
  resources/template/shop/res/img/left_right/1.png
  resources/template/shop/res/img/left_right/2.png
  resources/template/shop/res/img/left_right/3.png
  resources/template/shop/res/img/left_right/4.png
  resources/template/shop/res/img/left_right/5.png
  resources/template/shop/res/img/left_right/qq.png
  resources/template/shop/res/img/left_right/xx1.png
  resources/template/shop/res/img/left_right/xx2.png
  resources/template/shop/res/img/split.png
  resources/template/shop/res/img/title-bk.png
  zhenxun/builtin_plugins/shop/html_image.py
Labels: bug, resources

#1797 :tada: chore(version): 自动更新版本到 v0.2.4-2c97eea
  __version__
Labels: automated-update

#1821 ✨ 使用env中的日志等级记录日志
  zhenxun/services/log.py
Labels: enhancement

#1828 🐛 移除神秘药水2道具
  zhenxun/builtin_plugins/shop/goods_register.py
Labels: bug

#1831 :sparkles: 新增好感度/金币设置和详细帮助
  zhenxun/builtin_plugins/chat_history/chat_message_handle.py
  zhenxun/builtin_plugins/help/__init__.py
  zhenxun/builtin_plugins/help/_config.py
  zhenxun/builtin_plugins/help/_data_source.py
  zhenxun/builtin_plugins/help/_utils.py
  zhenxun/builtin_plugins/help/html_help.py
  zhenxun/builtin_plugins/help/normal_help.py
  zhenxun/builtin_plugins/help/zhenxun_help.py
  zhenxun/builtin_plugins/info/__init__.py
  zhenxun/builtin_plugins/info/my_info.py
  zhenxun/builtin_plugins/init/init_plugin.py
  zhenxun/builtin_plugins/nickname.py
  zhenxun/builtin_plugins/shop/__init__.py
  zhenxun/builtin_plugins/sign_in/__init__.py
  zhenxun/builtin_plugins/statistics/statistics_handle.py
  zhenxun/builtin_plugins/superuser/power/__ini__.py
  zhenxun/builtin_plugins/superuser/super_power.py
  zhenxun/builtin_plugins/web_ui/api/tabs/dashboard/data_source.py
  zhenxun/builtin_plugins/withdraw.py
  zhenxun/configs/utils/__init__.py
  zhenxun/models/plugin_info.py
  zhenxun/utils/platform.py
Labels: enhancement

#1834 :bug: 修复商店购买
  zhenxun/builtin_plugins/shop/_data_source.py
  zhenxun/builtin_plugins/shop/html_image.py
  zhenxun/builtin_plugins/shop/normal_image.py
  zhenxun/utils/message.py
Labels: bug

#1835 :bug: 修复Config add配置时显示问题
  zhenxun/builtin_plugins/init/init_config.py
  zhenxun/configs/utils/__init__.py
Labels: bug
