Repository zhenxun-org/zhenxun_bot, pull requests merged in 2025-02, with the labels that each got.

#1837 :bug: 修复添加插件依赖更新
  poetry.lock
  pyproject.toml
  tests/conftest.py
  zhenxun/builtin_plugins/admin/welcome_message/data_source.py
  zhenxun/builtin_plugins/platform/qq/group_handle/__init__.py
  zhenxun/builtin_plugins/platform/qq/group_handle/data_source.py
  zhenxun/builtin_plugins/plugin_store/__init__.py
  zhenxun/builtin_plugins/plugin_store/data_source.py
  zhenxun/builtin_plugins/sign_in/utils.py
  zhenxun/builtin_plugins/web_ui/api/tabs/main/data_source.py
  zhenxun/configs/config.py
  zhenxun/utils/decorator/retry.py
  zhenxun/utils/http_utils.py
  zhenxun/utils/message.py
  zhenxun/utils/platform.py
Labels: bug, dependencies

#1844 :arrow_up: Upgrade nonebot-plugin-htmlrender to version 0.6.0
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: dependencies

#1846 :sparkles: 提供一个插件好感度限制
  zhenxun/builtin_plugins/hooks/_auth_checker.py
  zhenxun/builtin_plugins/init/init_plugin.py
  zhenxun/configs/utils/__init__.py
  zhenxun/models/plugin_info.py
  zhenxun/models/sign_user.py
  zhenxun/utils/common_utils.py
Labels: enhancement

#1856 :construction_worker: Add CodeQL workflow for code security analysis
  .github/workflows/codeql.yml
Labels: ci

#1857 :wheelchair: Update bug report and feature request templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: ci

#1858 ✨ 提供qq协议端判断方法，广播添加to_me规则以及延迟
  README.md
  zhenxun/builtin_plugins/hooks/ban_hook.py
  zhenxun/builtin_plugins/superuser/broadcast/__init__.py
  zhenxun/builtin_plugins/superuser/broadcast/_data_source.py
  zhenxun/utils/platform.py
Labels: documentation, enhancement
